stages:
  - test
  - deploy

include:
  - template: Security/Dependency-Scanning.gitlab-ci.yml
  - template: Security/Secret-Detection.gitlab-ci.yml
  - template: Security/License-Scanning.gitlab-ci.yml
  - template: Security/SAST.gitlab-ci.yml
  
.prepare:
  stage: .prepare
  image: php:7.4
  cache:
    paths:
      - vendor/
  before_script:
    - apt-get update -yqq
    - apt-get install -yqq git libcurl4-openssl-dev libzip-dev
    - docker-php-ext-install curl zip
    - pecl install xdebug
    - docker-php-ext-enable xdebug
    - php --version
    - curl -sS https://getcomposer.org/installer | php
    - php composer.phar install
    - php composer.phar --version

test:
  stage: test
  extends: .prepare
  script:
    - echo 'not'
    #- php composer.phar fix-style
    #- php composer.phar check-style
    #- php composer.phar security

deploy:
  stage: deploy
  extends: .prepare
  only:
    refs:
      - main
  variables:
    BOM_SERVER: "$BOM_SERVER"
    BOM_KEY: "$BOM_KEY"
    BOM_PROJECT: "$BOM_PROJECT"
  script:
    - php composer.phar make-bom --exclude-dev
    - curl -X "POST" "$BOM_SERVER" -H "Content-Type:multipart/form-data" -H "X-Api-Key:$BOM_KEY" -F "project=$BOM_PROJECT" -F "bom=@bom.xml"
